# conda environment description file for the analysis-matt environment
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate analysis-matt
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   (analysis-matt)$ conda env update -f environment.yaml

name: analysis-matt

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - bottleneck
  - cliff
  - cmocean
  - coverage
  - dask
  - f90nml
  - gsw
  - ipdb
  - ipython
  - jupyterlab
  - lxml
  - matplotlib
  - nbsphinx
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pip
  - pytest
  - python=3
  - pytz
  - python-dateutil
  - pyyaml
  - requests
  - retrying
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - xarray
  - parcels
  - bottleneck
  - jupyterlab
  - cartopy
  - cmocean
  - ffmpeg
  - pytest
  - seaborn

  - pip:
    - angles
